"""
Test Extraction on Title Block Crops

Tests the VisionExtractor on the title block crops generated by the
multi-stage detection pipeline.
"""

import sys
from pathlib import Path
from PIL import Image

sys.path.insert(0, str(Path(__file__).parent))

from core.vision_extractor import VisionExtractor


def test_extraction_on_crops():
    """Test extraction on title block crops."""

    crop_dir = Path(r"C:\tb\blueprint_processor\output\full_pipeline")

    # Get title block crops
    crop_files = sorted(crop_dir.glob("*_titleblock.png"))

    if not crop_files:
        print("No title block crops found!")
        return

    print("="*80)
    print("EXTRACTION TEST ON TITLE BLOCK CROPS")
    print(f"Found {len(crop_files)} crops")
    print("="*80)

    # Initialize extractor
    extractor = VisionExtractor()

    if not extractor.is_available():
        print("ERROR: Vision API not available")
        return

    results = []

    # Test on a selection of crops
    test_crops = crop_files[:8]  # Test first 8

    for crop_path in test_crops:
        pdf_name = crop_path.stem.replace("_titleblock", "")
        print(f"\n{'='*60}")
        print(f"PDF: {pdf_name[:50]}")

        try:
            # Load crop image
            crop_img = Image.open(crop_path)
            print(f"  Crop size: {crop_img.size}")

            # Extract sheet title
            title_result = extractor.extract_title(crop_img)
            sheet_title = title_result.get('title', 'UNKNOWN')
            title_conf = title_result.get('confidence', 0)

            # Extract sheet number
            number_result = extractor.extract_sheet_number(crop_img)
            sheet_number = number_result.get('sheet_number', 'UNKNOWN')
            number_conf = number_result.get('confidence', 0)

            print(f"\n  EXTRACTED:")
            print(f"    Sheet Title:  {sheet_title}")
            print(f"    Title Conf:   {title_conf:.2f}")
            print(f"    Sheet Number: {sheet_number}")
            print(f"    Number Conf:  {number_conf:.2f}")

            results.append({
                'pdf': pdf_name[:35],
                'title': sheet_title,
                'title_conf': title_conf,
                'number': sheet_number,
                'number_conf': number_conf
            })

        except Exception as e:
            print(f"  ERROR: {e}")
            import traceback
            traceback.print_exc()

    # Summary
    print("\n" + "="*90)
    print("EXTRACTION SUMMARY")
    print("="*90)
    print(f"{'PDF':<35} {'Sheet #':>10} {'Sheet Title':<35}")
    print("-"*90)

    for r in results:
        title = r['title'][:32] + "..." if r['title'] and len(r['title']) > 35 else (r['title'] or "---")
        number = r['number'] or "---"
        print(f"{r['pdf']:<35} {number:>10} {title:<35}")

    # Stats
    titles_found = sum(1 for r in results if r['title'])
    numbers_found = sum(1 for r in results if r['number'])
    print("-"*90)
    print(f"Titles found: {titles_found}/{len(results)}")
    print(f"Numbers found: {numbers_found}/{len(results)}")


if __name__ == "__main__":
    test_extraction_on_crops()
